[workspace]
members = [
	"collator",
	"executor",
	"pallets/allocations",
	"pallets/amendments",
	"pallets/emergency-shutdown",
	"pallets/grants",
	"pallets/parachain-info",
	"pallets/reserve",
	"pallets/root-of-trust",
	"pallets/root-of-trust/rpc",
	"pallets/root-of-trust/rpc/runtime-api",
	"pallets/tcr",
	"pallets/token-dealer",
	"primitives",
	"runtime",
	"support"
]

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"